### ISSUE TITLE
确认登陆后还是没反应，是不是微信号必须实名认证才行？

### ISSUE THREAD

**Issue by zjrwtx** [yxw21/wechatgpt#4]
![image](https://user-images.githubusercontent.com/86822589/209607692-873cd65c-5eeb-4c0c-9d17-f436a09acb7e.png)

**Comment by yxw21** [comment]
不知道诶，我没有遇到过这种情况，要不你试试用一个经过实名认证的号。

**Comment by yxw21** [comment]
好像就是要实名认证
https://github.com/eatmoreapple/openwechat/issues/102

**Comment by zjrwtx** [comment]
> 好像就是要实名认证 [eatmoreapple/openwechat#102](https://github.com/eatmoreapple/openwechat/issues/102)

好的好的 请问现在是不是用chatgpt机器人还是很容易被微信封号

**Comment by yxw21** [comment]
我挂了有半个月了，都没啥事。尽量不触发wx风控应该就没啥事吧。

**Comment by zjrwtx** [comment]
> 
我之前基于另外一个项目搞得chatgpt微信机器人，后来被封了，请问你了解哪些行为可能会触发wx风控吗

**Comment by yxw21** [comment]
微信双开如果是IOS的话，你找个靠谱点的然后根据他们的建议来使用吧。
然后就是不要频繁的在陌生网络登录。
我的wx小号是使用过很久的，所以信用可能比较好？

**Comment by zjrwtx** [comment]
> 微信双开如果是IOS的话，你找个靠谱点的然后根据他们的建议来使用吧。 然后就是不要频繁的在陌生网络登录。 我的wx小号是使用过很久的，所以信用可能比较好？

好的好的 明白了 现在有个新问题，是不是我刚认证微信号，所以需要等一段时间才可以正常使用
![image](https://user-images.githubusercontent.com/86822589/209611692-bff9e55b-eddd-4301-ac57-7c51f3d23d45.png)

**Comment by yxw21** [comment]
这个提示是目前没有accesstoken，如果你提供了账号和密码此时应该正在自动登录过程中。登录时间可能很短可能很长。

参考 https://github.com/yxw21/wechatgpt#环境变量

**Comment by yxw21** [comment]
你也可以查看容器日志，docker logs -f xxxx

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209613150-78e0877e-8604-46ef-be60-b0595ca2cfb7.png)
我docker run参数填的是token，其他email和password参数我删掉了，为什么还是用账号密码登陆

**Comment by yxw21** [comment]
你用的是最新版的吗，docker pull yxw21/wechatgpt

**Comment by yxw21** [comment]
检查步骤
- 检查容器是否是最新版，不是的话重新拉一下
- 查看提供的accesstoken是否过期(最好重新获取下)
- 是否正确提供环境变量给到容器(docker exec -it xxxx env)

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209613812-3461061a-8b6c-41ac-8079-30851f8a44cc.png)
![image](https://user-images.githubusercontent.com/86822589/209613956-c8654682-d630-4b88-9a91-bbc3e981ec51.png)
![image](https://user-images.githubusercontent.com/86822589/209614278-ebd66059-9844-4c18-94d5-5d3160a718bd.png)
已经是最新版

**Comment by yxw21** [comment]
我[readme.md](https://hub.docker.com/r/yxw21/wechatgpt)写错了。应该是`docker pull yxw21/wechatgpt`。。我改过来了，你也重新拉取下最新版。`docker pull yxw21/wechatgpt`

**Comment by zjrwtx** [comment]
好的好的 我再试试

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209615744-ee20ac56-d449-4164-906d-ff8d9ac872c8.png)
重新试了，token也换了，还是老问题出现

**Comment by yxw21** [comment]
你给错了accesstoken，你这个看起来像是sessiontoken，accesstoken登录后访问https://chat.openai.com/api/auth/session

**Comment by zjrwtx** [comment]
哦哦 但是我改了accesstoken以后 还是一样authorization information is
being obtained，

**Comment by yxw21** [comment]
只要是`authorization information is being obtained`这个信息就说明accesstoken无效。
确定提供的是下图中的accesstoken吗
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/16237562/209618362-ff02c5fb-5495-4689-aa86-0422a59d6f74.png">.
确定之后，把之前启动的容器删除下重新运行。
然后`docker exec -it xxxx env`

**Comment by yxw21** [comment]
> ![image](https://user-images.githubusercontent.com/86822589/209613812-3461061a-8b6c-41ac-8079-30851f8a44cc.png) ![image](https://user-images.githubusercontent.com/86822589/209613956-c8654682-d630-4b88-9a91-bbc3e981ec51.png) ![image](https://user-images.githubusercontent.com/86822589/209614278-ebd66059-9844-4c18-94d5-5d3160a718bd.png) 已经是最新版

把这个重新贴一下。

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209620500-cae550f1-65ad-4551-b28d-059bfd7c7af6.png)
![image](https://user-images.githubusercontent.com/86822589/209620836-81c606e3-5d10-4738-9da2-dda2a75e2243.png)

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209620933-531214c9-9c36-438e-897f-187c44ae3bbc.png)确定这个accesstoken没错的

**Comment by yxw21** [comment]
现在还是回答的`authorization information is being obtained`吗

**Comment by zjrwtx** [comment]
> 现在还是回答的`authorization information is being obtained`吗

对的

**Comment by yxw21** [comment]
看下docker日志呢

**Comment by yxw21** [comment]
还有一种可能就是你提供的这个accesstoken即将在6小时内到期。这个时候就会被认定为无效，然后开始刷新。
你可以打开https://chat.openai.com/api/auth/session
然后f12执行下面代码看看你的accesstoken什么时候到期
```
new Date(JSON.parse(atob(JSON.parse(document.querySelector("pre").innerHTML).accessToken.split(".")[1])).exp * 1000)
```
<img width="836" alt="image" src="https://user-images.githubusercontent.com/16237562/209621915-3fe1f175-cca0-42e6-98b7-16c9b4ca7829.png">

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209621941-642ce04a-82bd-4e37-ae24-a4e7d119c0b0.png)
没有什么异常显示，就是还是authorization information is being obtained
![image](https://user-images.githubusercontent.com/86822589/209622142-196bae84-9569-43cb-b478-1ff94bef8855.png)

**Comment by yxw21** [comment]
我试一下docker版本，刚好我发现一个问题顺带一起解决。
我现在用的是二进制文件部署的。

**Comment by zjrwtx** [comment]
好的 那我等你更新信息

**Comment by yxw21** [comment]
我刚刚试了下docker版本没问题啊
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/16237562/209622973-04273419-f254-47ad-9c0d-ba7e2460c5eb.png">

**Comment by yxw21** [comment]
本地
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/16237562/209623621-4ecd3ee1-59d6-4143-a8f2-a0be278e08a3.png">

**Comment by zjrwtx** [comment]
啊这 你是在linux上部署的吗 我直接在win上试的

**Comment by yxw21** [comment]
一个是linux，一个是mac。
我没有windows，没测试过，不过应该是一样的。
你按下面步骤补充一些信息。
- docker images yxw21/wechatgpt --digests
- docker ps -a

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209624667-99ca7d57-35ef-4c35-bd54-1fac50318f6d.png)

**Comment by yxw21** [comment]
镜像是最新的，那你现在先停掉原来的容器`docker stop bf3ca84f97cb`，然后新启动一个容器再试试呢。

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209628348-8eac659c-ecb4-481d-86c1-7c44362ea6a2.png)
还是老问题，我linux也试了

**Comment by zjrwtx** [comment]
这个跟开代理没关系的吧

**Comment by zjrwtx** [comment]
accesstoken是开代理时候获取的，现在docker没有开代理啥的，不过应该没关联才对

**Comment by yxw21** [comment]
跟代理没关系，你那个是accesstoken没有获取到或者无效。我发了一个新版你重新拉取下试试。`docker pull yxw21/wechatgpt`

**Comment by yxw21** [comment]
新版增加了检测accesstoken，新版你运行后还是一样的错误贴上下面信息。
- docker images yxw21/wechatgpt --digests
- docker ps -a
- docker logs xxxx

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209653132-aaace614-c390-40a5-9460-a92fae576bf0.png)
![image](https://user-images.githubusercontent.com/86822589/209653173-84ef6475-fa39-46d1-8449-7805be0dd91f.png)
确实是token不对，但是我确实是按照你说的方式获取，不知道为啥还是不对

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209653263-b4e2bd9b-57f8-447d-8f25-513580967d0c.png)

**Comment by yxw21** [comment]
你看看你复制完没，然后你试试在命令行上用双引号把accesstoken包起来。
-e xxx="token"

**Comment by zjrwtx** [comment]
> 你看看你复制完没，然后你试试在命令行上用双引号把accesstoken包起来。 -e xxx="token"

确定复制完整了，还是不行，你方便支持远程帮助（向日葵软件之类的），搞了7个小时，几乎就是因为accesstoken的问题而卡死（手动落泪）

**Comment by yxw21** [comment]
加QQ吧。3136838255

**Comment by zjrwtx** [comment]
> 加QQ吧。3136838255

已申请

**Comment by yxw21** [comment]
已解决
