### ISSUE TITLE
部署到服务器上时候，想切换到容器内时候，总是提示容器已经停止运行，容器重启没几十秒就停止了，用了-d参数开启守护进程

### ISSUE THREAD

**Issue by zjrwtx** [yxw21/wechatgpt#5]
![image](https://user-images.githubusercontent.com/86822589/209678570-b47cebe7-b32c-4513-bf36-4cb99672dadd.png)

**Comment by yxw21** [comment]
补充一下容器日志

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209679444-0b66cc4c-1fa2-4a0a-a7f8-49688c6fb197.png)
ws连接超时

**Comment by yxw21** [comment]
不要加-f

**Comment by zjrwtx** [comment]
不加-f 也是同样的显示

**Comment by yxw21** [comment]
那你运行的时候不加-d呢，看看日志

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209681042-3e369012-3ce3-47bc-93e4-d43584aa9384.png)
同样的报错

**Comment by yxw21** [comment]
```
docker run -it xxxx
```

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/209681639-78a28c4f-5c5e-45b1-8379-c74a85439f58.png)

**Comment by zjrwtx** [comment]
> ![image](https://user-images.githubusercontent.com/86822589/209681639-78a28c4f-5c5e-45b1-8379-c74a85439f58.png)
> 

现在Win上面的docker也经常自动关闭容器，不清楚为什么

**Comment by yxw21** [comment]
检查下是不是内存问题。

**Comment by zjrwtx** [comment]
我换了服务器系统清空一波后，现在行了
