### ISSUE TITLE
两个人同时向bot提问会出现Only one message at a time

### ISSUE THREAD

**Issue by yuanwangz** [yxw21/wechatgpt#7]
完整信息：{"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}

是不是因为用的同一个会话的原因，能否实现不同人使用不同的chatgpt会话？

**Comment by yxw21** [comment]
之前测试过好像是因为chatgpt的限制，你自己可以再测试一下。
浏览器打开两个标签页面，然后每个标签页面使用不同的会话同时提一个比较耗时的问题，你应该就会收到这个错误消息。

**Comment by yuanwangz** [comment]
> 之前测试过好像是因为chatgpt的限制，你自己可以再测试一下。
> 浏览器打开两个标签页面，然后每个标签页面使用不同的会话同时提一个比较耗时的问题，你应该就会收到这个错误消息。

是的，在浏览器使用多个会话同时提问也会有这个问题
