### ISSUE TITLE
破解验证码能支持使用2Captcha吗？

### ISSUE THREAD

**Issue by yuanwangz** [yxw21/wechatgpt#8]
看了下nopecha是按订阅收费4.99美元/月，只有bot用的话有点浪费了，2Captcha好像是按量收费。 [2Captcha](https://2captcha.com/api-docs)

**Comment by yxw21** [comment]
最近没时间诶，等过段时间看看吧。或者你自己clone然后增加一个2captcha。实在不行也可以考虑用accesstoken，应该是7天有效期的。
